### ISSUE TITLE
Not working on 2.1.46

### ISSUE THREAD

**Issue by euu2021** [AnKing-VIP/anki-field-autocomplete#1]
Hi!

I just tested the adddon here in Anki 2.1.46, but nothing happens. I see the config options under Anking in the menubar, but nothing shows up in the add note screen.

Here is my addons list:
![image](https://user-images.githubusercontent.com/77707706/129959113-1d662c69-7a13-4aa3-b20f-2665652bf2a5.png)

Thanks,

**Comment by RisingOrange** [comment]
Hi! Have you tried disabling the other add-ons and restarting Anki?

If this doesn't work please open Anki, go to Help → About, click on "Copy Debug Info", and post your result here.

**Comment by euu2021** [comment]
I tried to disable the other addons. Here is the debug:


    
    Anki 2.1.46 (94913ec2) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2021-08-18 10:31:58
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Field AutoComplete ['511710206', 2021-08-17T17:43, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    511710206
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Anki Zoom ['538879081', 2020-04-03T21:20, 'v1.1.3', mod]
    Auto Sync ['501542723', 2021-08-08T09:30, 'None', '']
    Autosync 21 ['1726633659', 2019-03-08T20:58, 'None', '']
    BetterSearch ['1052724801', 2021-08-04T17:51, 'None', '']
    Change Card Creation Times ['217650262', 2019-03-04T23:59, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T23:21, 'None', '']
    No Distractions Full Screen Clean review interface  TabletTouch support ['1049863218', 2020-08-13T19:59, 'v4.1.8', mod]
    Opening the same window multiple time ['354407385', 2020-05-15T21:59, 'None', '']
    PDF Glossary Exporter ['pdf_glossary', 2019-08-19T09:35, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T10:23, 'None', '']
    See Previous Card Ratings in Reviewer ['1906641654', 2021-08-09T16:20, 'None', mod]
    Speed Focus Mode ['speed_focus_mode', 2021-04-19T08:38, 'None', '']
    extended editor for field for tables searchreplace ['805891399', 2020-11-23T21:08, 'None', '']

**Comment by RisingOrange** [comment]
This should be fixed in the current version. (It was uploaded to AnkiWeb today)

**Comment by euu2021** [comment]
Now, it's perfect!
