### ISSUE TITLE
Display last used items first?

### ISSUE THREAD

**Issue by ankidoc** [AnKing-VIP/anki-field-autocomplete#13]
Is there any possibilty that the items that show up upon clicking the field displays the last used items first?
It don't see a specific order actually, or maybe this feature is available but overlooked the activating button?

thanks

**Comment by abdnh** [comment]
I vote to make displaying the last created items first the default behavior. It's a trivial one-line change, so if @AnKingMed agrees, I can push the change.

**Comment by AnKingMed** [comment]
I agree. Sounds good to me

**Comment by AnKingMed** [comment]
@AnKing-Forrest @DrGenTraum we can build a new release and release this on ankiweb now (might be good to do a quick test)

**Comment by AnKing-Forrest** [comment]
I tested this, it works, and it is now released on AnkiWeb
