### ISSUE TITLE
No longer works on 23.12.1

### ISSUE THREAD

**Issue by imlutr** [AnKing-VIP/anki-field-autocomplete#15]
#### Problem description

First off, thanks for the great plugin! ❤️ 

Sadly, it seems that it no longer works on Anki 23.12.1. I don't get any errors on start-up, but the "A" button no longer appears for fields, nor does F4 work.

#### Checklist

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.

#### What Anki version are you using?

```
23.12.1
```

#### Error message (if any)

```
None
```

**Comment by luca-trusca** [comment]
Okay... Now it suddenly started working, so I guess I'm closing this 😅
