### ISSUE TITLE
AutoComplete not working on first added card

### ISSUE THREAD

**Issue by Evgeny973** [AnKing-VIP/anki-field-autocomplete#19]
The search does not work and the "A" toggle does not show up when you add the first card.

 - [X] I've restarted Anki to see if it helps
 - [X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 
I'm using Version ⁨24.06.2

I'm attaching a short videorecording to demonstrate the issue.

https://github.com/AnKing-VIP/anki-field-autocomplete/assets/174269148/21534ec2-d49d-42ba-901d-9ff9838d1b4a

**Comment by AnKingMed** [comment]
@damronatron can you look into this and see if it's happening on your end as well?

**Comment by Evgeny973** [comment]
@AnKingMed any feedback on this please?

**Comment by damronatron** [comment]
@AnKingMed curiously, this is happening to me too. But when I was a third year student making cards for missed Uworld questions, I do not remember this happening. 
See clip: 
https://jmp.sh/nHR5qBQ4

**Comment by AnKingMed** [comment]
@RisingOrange do you have any idea why this might be?

**Comment by RisingOrange** [comment]
I made a fix and released a new version!

**Comment by AnKingMed** [comment]
Thank you!

**Comment by Evgeny973** [comment]
Great, thank you guys! I've updated the rating on the add-on page as well. Much appreciated!
